# Generated by Django 4.2.6 on 2023-10-30 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_blog_post_title_alter_product_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_current_version',
            field=models.BooleanField(default=False, verbose_name='Признак текущей версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
    ]
