# Generated by Django 4.2.6 on 2023-11-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=89999999999, max_length=50, verbose_name='страна'),
            preserve_default=False,
        ),
    ]
